name: personal_dropdown_example
description: Demonstrates how to use the personal_dropdown plugin.
publish_to: 'none' 

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  personal_dropdown:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
