name: personal_dropdown
description: A new Flutter plugin project.
version: 1.0.7
homepage: No Home Page

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.personal_dropdown
        pluginClass: PersonalDropdownPlugin
      ios:
        pluginClass: PersonalDropdownPlugin
      linux:
        pluginClass: PersonalDropdownPlugin
      macos:
        pluginClass: PersonalDropdownPlugin
      windows:
        pluginClass: PersonalDropdownPluginCApi
      web:
        pluginClass: PersonalDropdownWeb
        fileName: personal_dropdown_web.dart
